@startuml

component MonitorMeStation {
  [Admin Services]
  [Security Services]
  [Web Services]
  [Data Storage Service]
  [Nurse Station Manager Service]
}

component NurseStation {
  [SensorDeviceServices]
  [ResourceManagerService]
  [DeviceBrokenMonitor]
}

component RedundantNurseStation

MonitorMeStation -down-> NurseStation : manages
MonitorMeStation -down-> RedundantNurseStation : manages

SensorDeviceServices --> PhysicalSensors
SensorDeviceServices --> RedundantPhysicalSensors
DeviceBrokenMonitor  --> PhysicalSensors
DeviceBrokenMonitor  --> RedundantPhysicalSensors
ResourceManagerService  --> PhysicalSensors
ResourceManagerService  --> RedundantPhysicalSensors

note top of MonitorMeStation: capable of managing 25 nurse stations
note bottom of NurseStation: capable of managing 20 patients

@enduml
